version: 2.1

# orbs:
#   node: circleci/node@5.1.0

# orbs 
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.1

jobs:
  build:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run:
          command: |
            npm install
      - run:
          command: |
            npm run test
  # build_and_test:
  #     docker:
  #       - image: cimg/node:16.16.0
  #     steps:
  #       - checkout
  #       - run:
  #           name: Run tests
  #           command: npm run test-ci
  #       - run:
  #           name: Copy tests results for storing
  #           command: |
  #             mkdir test-results
  #             cp test-results.xml test-results/
  #           when: always
  #       - store_test_results:
  #           path: test-results
  #       - store_artifacts:
  #           path: test-results

  # build with cache of downloads:
  # build_and_test:
  #     docker:
  #       - image: cimg/node:16.16.0
  #     steps:
  #       - checkout
  #       - restore_cache:
  #           keys:
  #             - v1-npm-deps-{{ arch }}-{{ checksum "package-lock.json" }}
  #             - v1-npm-deps-{{ arch }}-
  #             - v1-npm-deps-
  #       - run:
  #           command: |
  #             npm install
  #       - save_cache:
  #           paths:
  #             - node_modules
  #           key: v1-npm-deps-{{ arch }}-{{ checksum "package-lock.json" }}
  #       - run:
  #           command: |
  #             npm run test-ci

  # # Now with cache in Orbs
  build_and_test:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm run test-ci  

  # now with docker build
  build_docker_image:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: false
        - docker/check
        - docker/build:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            tag: 0.1.<< pipeline.number >>
        - docker/push:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            tag: 0.1.<< pipeline.number >>  
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - build_docker_image